### ISSUE TITLE
Loading state for Locations on home page

### ISSUE THREAD

**Issue by orta** [artsy/Emergence#11]
@owendodd 
I'd like to propose something like this for when we are still loading shows for a location

![screen shot 2015-10-12 at 10 59 22](https://cloud.githubusercontent.com/assets/49038/10425538/56243faa-70d0-11e5-97c2-1da7f86c8fd2.png)

and maybe some grey placeholders?

**Comment by orta** [comment]
![screen shot 2015-10-12 at 11 01 05](https://cloud.githubusercontent.com/assets/49038/10425569/8e550fc6-70d0-11e5-9bbe-c41cf0cd0848.png)

**Comment by owendodd** [comment]
I agree this is a good solution. I wonder if we even need the spinner, it seems to load quite quickly, even when you scroll through a bunch. 

If we do keep it, I think it should be to the right of the title to avoid the text jumping when it disappears. 

Thoughts on no spinner though?

**Comment by katarinabatina** [comment]
@orta @owendodd I think the grey boxes are sufficient, would be nice if they could "glimmer" a bit, I think this works pretty well on Facebook http://cl.ly/2n3R1E3m3w2s (notice the grey dummy content has a slight color transition)

**Comment by orta** [comment]
I"m also happy with the load times, can re-open for a loading state for images if we choose.
