### ISSUE TITLE
Show number of available shows on a location?

### ISSUE THREAD

**Issue by orta** [artsy/Emergence#12]
![screen shot 2015-10-12 at 13 52 34](https://cloud.githubusercontent.com/assets/49038/10428333/84e1055e-70e8-11e5-99ab-8631c8233cb6.png)

Thinking out loud, we only see 3 thumbnails, there's no way to know how many shows are on each location or that it's worth going sideways. Copy comes from https://www.artsy.net/shows

**Comment by owendodd** [comment]
This is smart. Let's do it. Only change I would make is to capitalize 'Current' and 'Shows'

**Comment by katarinabatina** [comment]
I'd float those counts out to the right they seem to be floating a bit next to the titles, 
![image](https://cloud.githubusercontent.com/assets/6482926/10611114/a13c509c-7718-11e5-820c-c6e37ccd93ec.png)

or drop them under the section header

**Comment by orta** [comment]
This is in.
