### ISSUE TITLE
Indicate there is content below the fold on the show view.

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#13]
Alternative to the 3 dots in the prototype. Small arrow at the bottom of the screen.

![artsy app copy 18 1x](https://cloud.githubusercontent.com/assets/3196536/10441656/66269e04-7119-11e5-952d-a3dfde4a8852.png)
![artsy app copy 28 1x](https://cloud.githubusercontent.com/assets/3196536/10441657/66298af6-7119-11e5-893f-25d805c40bcb.png)

Thoughts?

cc @katarinabatina looking at this again and I feel like this is a more obvious / nicer solution

**Comment by katarinabatina** [comment]
@owendodd @orta this is feeling good, closing!
