### ISSUE TITLE
Reduce Z height of active show?

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#16]
Is it possible to make the active show less 'raised'. Currently the thumbnail is casting a shadow on the title of the show. Not sure how much control we have over this. 

![img_4685](https://cloud.githubusercontent.com/assets/3196536/10464800/898b8e18-71b9-11e5-93c2-2a819e197d0f.JPG)
(sorry for the sketchy picture, don't think you can screenshot on the TV)

**Comment by owendodd** [comment]
Ugh, not sure why it is upside down either, clicking on it flips it though

**Comment by orta** [comment]
Nope, no official control alas :-1: 

I will look into faking it though.

**Comment by owendodd** [comment]
I guess the other option is just to increase padding so the shadow doesn't hit the text

**Comment by orta** [comment]
For the artworks I move the artwork metadata left and down in the same animation cycle to make it work

**Comment by orta** [comment]
https://forums.developer.apple.com/thread/22150

from fletcher:

```
    let yRotationMotionEffect = UIInterpolatingMotionEffect(keyPath: "layer.transform", type: .TiltAlongHorizontalAxis)  
    let xRotationMotionEffect = UIInterpolatingMotionEffect(keyPath: "layer.transform", type: .TiltAlongVerticalAxis)  
    let xMovementMotionEffect = UIInterpolatingMotionEffect(keyPath: "center.x", type: .TiltAlongHorizontalAxis)  
    let yMovementMotionEffect = UIInterpolatingMotionEffect(keyPath: "center.y", type: .TiltAlongVerticalAxis)  
```

```
        let m34 = CGFloat(1.0 / -1250)  
        let angle = CGFloat(minMaxAngle * M_PI / 180.0)  

        var baseTransform = CATransform3DIdentity  
        baseTransform.m34 = m34  

        var rotateYmin = baseTransform  
        rotateYmin = CATransform3DRotate(rotateYmin, angle, 0.0, 1.0, 0.0);  

        var rotateYmax = baseTransform  
        rotateYmax = CATransform3DRotate(rotateYmax, -1 * angle, 0.0, 1.0, 0.0);  

        yRotationMotionEffect.minimumRelativeValue = NSValue(CATransform3D: rotateYmin)  
        yRotationMotionEffect.maximumRelativeValue = NSValue(CATransform3D: rotateYmax)  

```

**Comment by orta** [comment]
This is _not_ gonna happen, threw some time at it today and got nowhere.
