### ISSUE TITLE
About Artsy Page

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#21]
Initial comps for this page:

![artsy app copy 19 1x](https://cloud.githubusercontent.com/assets/3196536/10529013/54852980-7368-11e5-9e70-88efca0eb9da.png)
![artsy app copy 31 1x](https://cloud.githubusercontent.com/assets/3196536/10529014/5486742a-7368-11e5-9cf7-ac8c1ac62937.png)

I'm imagining the background to be a autoplay slideshow. Similar to https://www.artsy.net/about

I am wondering if the button state can start as inactive and then any movement would target it. Thoughts? Also, do all 'active' objects need to use the z-space styling or can we do other types of style changes like shown. 

Clicking the button would pop the default keyboard. Couldn't figure out exactly what it looks like, all I saw was this: 

![ui-elements-text-linear](https://cloud.githubusercontent.com/assets/3196536/10529079/dacdd730-7368-11e5-9364-2ba22cbeb92d.png)

And this: https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UITextInputTraits_Protocol/index.html#//apple_ref/c/tdef/UIKeyboardType

**Comment by owendodd** [comment]
cc @orta @katarinabatina

**Comment by katarinabatina** [comment]
@orta haven't seen the full version of this, how much work is left on this item?

**Comment by orta** [comment]
:+1: in, will ship a build asap
