### ISSUE TITLE
Consistent margins

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#24]
Can we make the margins on all screens the same. Should be 60px on all sides. 

![screen shot 2015-10-19 at 5 48 34 pm](https://cloud.githubusercontent.com/assets/3196536/10592480/5ae1a694-768a-11e5-834f-c330a19a0eb5.png)
![screen shot 2015-10-19 at 5 51 57 pm](https://cloud.githubusercontent.com/assets/3196536/10592482/5ae82af0-768a-11e5-8965-3921234f6372.png)
![screen shot 2015-10-19 at 5 52 58 pm](https://cloud.githubusercontent.com/assets/3196536/10592481/5ae70b8e-768a-11e5-9db5-71c946b542a7.png)

**Comment by orta** [comment]
in the sketch files these are all 80px? Happy to change, but want to be certain, it's a lot of fiddling that I'd rather not do till I'm 100%

**Comment by orta** [comment]
![screen shot 2015-10-20 at 08 21 37](https://cloud.githubusercontent.com/assets/49038/10600563/9899897e-7703-11e5-9a96-383758d6d2dc.png)

**Comment by katarinabatina** [comment]
@owendodd what's the word here?

**Comment by owendodd** [comment]
Yes 60px everywhere is the way to go. Thanks Orta!

**Comment by orta** [comment]
before we do this, it's already pretty tight on my TV and [apple recommend being wary](https://developer.apple.com/tvos/human-interface-guidelines/visual-design/) of being closer than 90 px from the edge

![screen shot 2015-10-20 at 15 35 51 1](https://cloud.githubusercontent.com/assets/49038/10610555/4c87d210-7740-11e5-8155-bcdca0b9a517.png)

**Comment by owendodd** [comment]
Ok, Let's follow their guidelines and go with 60 top + bottom. 90 right + left.

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
this is in
