### ISSUE TITLE
Alignment on home screen

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#25]
These should all me left aligned when the left thumbnail is not selected. 

![screen shot 2015-10-19 at 5 54 28 pm](https://cloud.githubusercontent.com/assets/3196536/10592513/8e26b058-768a-11e5-9fa9-ccbb0d182b1e.png)

**Comment by orta** [comment]
These are now lined up :+1:

**Comment by katarinabatina** [comment]
looks good
