### ISSUE TITLE
Pre-cache images?

### ISSUE THREAD

**Issue by orta** [artsy/Emergence#28]
- [x] Show thumbnails
- [x] Show artworks
- [x] Show install shots
- [x] Artwork View Controllers?

They will need to cancel when a VC disappears though.

**Comment by katarinabatina** [comment]
@orta I can really FEEL the show installs not being cached, upwards of 14 seconds before I am getting anything once I click into shows...any chance of getting that in before EOD tomorrow?

**Comment by orta** [comment]
So, the problem here is that we have to make multiple network calls in order to get the install shots, so precaching here is super slow - it is actually doing it, but I was wondering if I could find a better way to do it.

**Comment by orta** [comment]
I found _a_ way, which seems to hit pretty often.

Because a show's thumbnail could either be an install shot or an artwork, I check to see if it's already downloaded the show installation shot image, move that to be the first installation shot we show and use the pre-cached version.
