### ISSUE TITLE
Artsy Apple TV Press Image

### ISSUE THREAD

**Issue by katarinabatina** [artsy/Emergence#29]
We need to scramble a press image together

**Comment by owendodd** [comment]
Is this for the app store? Or just for general press?

**Comment by katarinabatina** [comment]
This is general press, @orta any sense of what app store will look like? What kind of shots we'll need?

**Comment by orta** [comment]
For the press, that's much harder to gauge. I'd say start with the app store ones then we can manipulate on request.
For app store we'll need 5 of 1920 \* 1080 images .

**Comment by katarinabatina** [comment]
app store images, separate issue https://github.com/artsy/Emergence/issues/32 for press image i've got a meeting with Nick tomorrow. @owendodd time best spent today would be starting in on app store images and solving the press release/about show section

**Comment by orta** [comment]
Calling this done for now until we get some more news, we should try get our communications people in the loop too. :+1:

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/10672766/08c887f0-78c0-11e5-8d47-d4c5f59f209c.png)

**Comment by katarinabatina** [comment]
@orta

**Comment by orta** [comment]
nice book choices!

**Comment by orta** [comment]
Let's call this closed as #51 covers a more concrete example
