### ISSUE TITLE
App Store Images

### ISSUE THREAD

**Issue by katarinabatina** [artsy/Emergence#32]
For app store we'll need 5 of 1920 \* 1080 images

**Comment by katarinabatina** [comment]
1 http://cl.ly/image/2e0g1k0K1u0q
2 http://cl.ly/image/1r0J2k3p4743
3 http://cl.ly/image/1J3n0w2m040X
4 http://cl.ly/image/1E1B0W2G1007
5 http://cl.ly/image/3F0b32180P1b

**Comment by owendodd** [comment]
@katarinabatina Small typo on the fourth image!

**Comment by katarinabatina** [comment]
thank's @owendodd haven't uploaded the edits yet will do in a moment

**Comment by katarinabatina** [comment]
@owendodd @orta updated links up above

**Comment by owendodd** [comment]
@katarinabatina :ok_hand:

**Comment by orta** [comment]
These are shipped to iTunes
