### ISSUE TITLE
Solve legibility for About Show and Press Release

### ISSUE THREAD

**Issue by katarinabatina** [artsy/Emergence#33]
type currently too small but some of those press releases are also very long. Suggestion to pull out the show description make the type larger, truncate the press release

**Comment by owendodd** [comment]
![artsy app copy 17 1x](https://cloud.githubusercontent.com/assets/3196536/10616129/935de38c-7731-11e5-9cff-0119195d4491.png)
![artsy app copy 22 1x](https://cloud.githubusercontent.com/assets/3196536/10616128/93589e04-7731-11e5-9861-bbb37de8e6bf.png)
![artsy app copy 25 1x](https://cloud.githubusercontent.com/assets/3196536/10616127/93532dac-7731-11e5-930a-b0865a223c75.png)

**Comment by owendodd** [comment]
@orta

**Comment by orta** [comment]
OK, we're good here now :+1:
