### ISSUE TITLE
Make Artwork titles #666

### ISSUE THREAD

**Issue by owendodd** [artsy/Emergence#37]
![screen shot 2015-10-20 at 12 19 05 pm](https://cloud.githubusercontent.com/assets/3196536/10613829/f7b92830-7724-11e5-8493-4d97768efbaa.png)

**Comment by orta** [comment]
haha, took me a while to figure what you mean here :D

**Comment by orta** [comment]
I was like "There's no issue 666 yet?!"

**Comment by owendodd** [comment]
lolol

**Comment by orta** [comment]
This is in.
