### ISSUE TITLE
Custom UI above the keyboard

### ISSUE THREAD

**Issue by orta** [artsy/Emergence#40]
We need to customise the phone number input page:

![screen shot 2015-10-21 at 14 56 00](https://cloud.githubusercontent.com/assets/49038/10638651/e327793c-7803-11e5-8bad-1dff3ef0f362.png)

It needs to be able to:
- Show a "Enter your phone number"
- Show a "Your phone number is wrong" kind of messages
- Have a cancel button, cause we're using the "Send" button to send the API call instead of closing the window thing. 

You can probably grab a tvOS sketch file, cause this can't really be a mix of artsy design + apple design, that'd be weird.

Mine so far:

![screen shot 2015-10-21 at 14 53 56](https://cloud.githubusercontent.com/assets/49038/10638622/c8b5c32e-7803-11e5-90d3-7bf1ab33c677.png)

**Comment by owendodd** [comment]
How's something like this?

The error message would only show when there was an error obviously..

<img width="913" alt="screen shot 2015-10-21 at 10 52 08 am" src="https://cloud.githubusercontent.com/assets/3196536/10640228/d9252230-77e1-11e5-8bc6-9dd22ae4bfd8.png">

**Comment by owendodd** [comment]
And the colors are also off just because that was the tvOS file I had

**Comment by orta** [comment]
almost, we can't put the cancel button there alas, has to awkardly sit _above_ the numbers :/

**Comment by owendodd** [comment]
Ahh oh well, that's fine.

**Comment by owendodd** [comment]
So we have to do something like this?

![form copy 2](https://cloud.githubusercontent.com/assets/3196536/10647710/fcde3312-7807-11e5-87f2-2949e617b9f6.png)

**Comment by owendodd** [comment]
Or could we do this?

![form copy](https://cloud.githubusercontent.com/assets/3196536/10647719/0679b784-7808-11e5-8969-eeca31d623a8.png)
![form](https://cloud.githubusercontent.com/assets/3196536/10647718/06769aa4-7808-11e5-9500-be29020b1894.png)

**Comment by orta** [comment]
nope, only in the purple space - like in my photo. It might be worth me trying to hack it tomorrow though

**Comment by owendodd** [comment]
haha ok got it it think

so like so?

<img width="895" alt="screen shot 2015-10-21 at 3 35 46 pm" src="https://cloud.githubusercontent.com/assets/3196536/10647927/72b308d2-7809-11e5-88f7-fea6f0db4eef.png">

**Comment by orta** [comment]
Hah, yep

its got this cute diamond shape thing going on

:diamonds:

**Comment by orta** [comment]
OK this is in. When it sends - we show this:

![screen shot 2015-10-22 at 08 19 06](https://cloud.githubusercontent.com/assets/49038/10659158/a3d0f2d0-7895-11e5-8708-648f716fff3d.png)
