### ISSUE TITLE
Make a launch image

### ISSUE THREAD

**Issue by orta** [artsy/Emergence#44]
https://developer.apple.com/tvos/human-interface-guidelines/icons-and-images/#launch-image

should be a png of our AuthVC

**Comment by katarinabatina** [comment]
still dont see how this is different than:

![image](https://cloud.githubusercontent.com/assets/6482926/10648423/42309e92-780c-11e5-9881-95cb5ba21c6e.png)

**Comment by orta** [comment]
it will be that ^

**Comment by orta** [comment]
this is in.
