### ISSUE TITLE
app Top Shelf Image

### ISSUE THREAD

**Issue by katarinabatina** [artsy/Emergence#46]
http://cl.ly/image/2D022R3V1T46

**Comment by katarinabatina** [comment]
edit: http://cl.ly/image/2f2D2I3F182K

**Comment by katarinabatina** [comment]
another option http://cl.ly/image/0h450q0k3o1O

**Comment by orta** [comment]
my pref is the "art world" - moved it in, happy to change

**Comment by orta** [comment]
in
