### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by pincheira** [artsy/Emergence#58]
Hi guys.

I installed the OSS keys and did a 'bundle exec pod install' but it throws:

```
[!] Error installing Analytics
[!] /usr/local/bin/git checkout --quiet 2eee4da68f53a005d8db966a21f6319241e12afd

fatal: reference is not a tree: 2eee4da68f53a005d8db966a21f6319241e12afd
```

Any ideas to get it running? Thank you!

jp

**Comment by orta** [comment]
I've pushed some changes that should fix this!

**Comment by pincheira** [comment]
@orta thanks a lot! :+1:
